config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member 
      put 'add_user', on: :member 
    end
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan


end

app/views/common/_navbar.html.erb
<nav class="lato navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span>
          <%= link_to ("<i class='fa fa-graduation-cap'></i> " +'Петар Ристески').html_safe, root_path, 
                                                                                class: "navbar-brand" %>
        </span>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
         
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="user-name">
              
            </li>
            <li><%= link_to('Logout', destroy_user_session_path, class: 'nav-link', title: 'Logout', :method => :delete) %></li>
          <% else %>
            <li><%= link_to('Sign In', new_user_session_path, class: 'nav-link', title: 'Sign In') %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
<% if current_user %>
<div id="links">
    <div class="links">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user && current_user.is_admin? %>
            <li><%= link_to "<i class='fa fa-users'></i> Add Members".html_safe,
                        new_member_path,
                        class: 'nav-link' %></li>
            <li><%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path,
                                                          class: 'nav-link' %></li>
          <% end %>
          
          <li><%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile', class: 'nav-link' %></li>
        </ul>
      </div>
    </div>
  </div><br>
<% end %>